repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      # ruff format
      - id: ruff-format
        name: ruff format
        description: Format code with ruff
        
      # ruff check
      - id: ruff
        name: ruff check
        description: Lint code with ruff
        args: [--fix]

  # pytest
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]